# Generated by Django 3.1.7 on 2021-03-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210315_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(3, 'admin'), (2, 'teacher'), (1, 'student')], primary_key=True, serialize=False),
        ),
    ]
