# Generated by Django 3.1.7 on 2021-06-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='image/no_image.png', upload_to='image/'),
        ),
    ]
