# Generated by Django 3.1.7 on 2021-05-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapes', '0002_alter_escape_queue_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='escapequeue',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
