name: DoranDoran django CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
      JWT_SECRET_KEY: ${{ secrets.TEST_JWT_SECRET_KEY }}
      JWT_ALGORITM: ${{ secrets.TEST_JWT_ALGORITM }}
      DJANGO_SETTINGS_MODULE: config.settings.deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run django test
        run: python dorandoran/manage.py test
