# Generated by Django 3.1.7 on 2021-03-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210315_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(4, 'lated'), (2, 'denied'), (1, 'accepted'), (3, 'waiting')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Escape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(default='reason', max_length=100, verbose_name='reason')),
                ('start_at', models.DateTimeField(verbose_name='start time')),
                ('end_at', models.DateTimeField(verbose_name='end time')),
                ('applyer_id', models.ForeignKey(db_column='applyer_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('status', models.ManyToManyField(to='escape.Status')),
            ],
            options={
                'db_table': 'Escape',
            },
        ),
    ]
