# Generated by Django 3.1.7 on 2021-03-16 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210316_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escape',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('reason', models.CharField(default='reason', max_length=100, verbose_name='reason')),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'denied'), (4, 'expired'), (1, 'accepted'), (3, 'waiting')], default=3)),
                ('start_at', models.DateTimeField(verbose_name='start time')),
                ('end_at', models.DateTimeField(verbose_name='end time')),
                ('applyer_id', models.ForeignKey(db_column='applyer_id', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Escape',
            },
        ),
    ]
